version: "3.8"

services:
  postgres:
    image: "postgres:13"
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./setup/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app_network

volumes:
  postgres_data: {}

networks:
  app_network: {}
